export const FETCH_CORRECTIONS_FOR_SENTENCES_INIT =
    'FETCH_CORRECTIONS_FOR_SENTENCES_INIT';
export const FETCH_CORRECTIONS_FOR_SENTENCES_SUCCESS =
    'FETCH_CORRECTIONS_FOR_SENTENCES_SUCCESS';
export const FETCH_CORRECTIONS_FOR_SENTENCES_ERROR =
    'FETCH_CORRECTIONS_FOR_SENTENCES_ERROR';
